name: Update Documentation

on:
  pull_request:
    branches: [ master ]

jobs:
  documentation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install sphinx
    - name: set up gh-pages branch
      env:
        VERSION: ${{ github.event.release.tag_name }}
      run: |
        git clone --single-branch --branch gh-pages https://github.com/AlexsLemonade/refinebio-py.git doc-output
        ls
        cd docs
        make github
        cd ..
        cd doc-output
        mv ./html/ ./docs/
        ls
        git add .
        git config --global user.name 'Documentation Robot'
        git config --global user.email '<>'
        git commit -m "updating docs for $VERSION"
        git push origin gh-pages
        