name: Rebuild and Upload Docs

on: push
  # release:
  #   types: [published]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r docs-requirements.txt
    # - name: Pull Master Branch
    #   run: git pull origin master
    - name: Build and publish
      env:
        VERSION: ${{ github.event.release.tag_name }}
      run: |
        git fetch
        git checkout gh-pages
        git pull origin master
        cd docs-input
        make github
        cd ../docs
        git add .
        git commit -m "Update docs for version $VERSION"
        git push origin gh-pages
